#!/bin/bash

declare -A parm_map

#echo $0 "test: [$1] [$2] [$3]" > /dev/kmsg

parm_map[sco]="sequential_cutoff"
parm_map[crdthr]="cache/congested_read_threshold_us"
parm_map[cwrthr]="cache/congested_write_threshold_us"
parm_map[sequential_cutoff]="sequential_cutoff"
parm_map[congested_read_threshold_us]="cache/congested_read_threshold_us"
parm_map[congested_write_threshold_us]="cache/congested_write_threshold_us"

for i in `cat /proc/cmdline`
do
    [[ "$i"  =~ ^bcache[.][0-9]+=.* ]] || continue
    DEV=${i%%=*}
    ARGS=${i#*=}

    DEV=${DEV%%.*}${DEV#*.}
    [[ "$DEV" == "$1" ]] || continue

    IFS=","
    for i in $ARGS
    do
        ARG=${i%%:*}
        VAL=${i#*:}
        FN="${parm_map[${ARG}]}"
        [ "$FN" == "" ] && continue

        FILE=/sys/block/$1/bcache/$FN
        echo "$0: write \"$VAL\" to \"$FILE\"" > /dev/kmsg
        echo "$VAL" > "$FILE"
    done
done

